### ISSUE TITLE
Missing headers in the repository

### ISSUE THREAD

**Issue by DavidMansolino** [epfl-disal/ns34webots#1]
According to this file: https://github.com/epfl-disal/ns34webots/blob/ad8d9629568c17b5df8b92db855c64aa448ff001/facilities/wscript#L17

Two headers are missing from the repository:
  - model/Vec2d.h
  - model/vehicle-data.h

**Comment by DavidMansolino** [comment]
@gjornod can you add these files if you still have them?

**Comment by gjornod** [comment]
Fixed in cc12b8060f2219094eb1a2450f12975c22d0151c
Note that thanks to the `const void *data` in [`webots_radio_send`](https://github.com/epfl-disal/ns34webots/blob/cc12b8060f2219094eb1a2450f12975c22d0151c/webots/webots_ns3.cc#L249), vehicle_data is not the only type one can send with the radio, as long as the size is consistent.

**Comment by DavidMansolino** [comment]
Perfect thank you.

I just tested and the whole compilation process is now running smoothly.
